### ISSUE TITLE
Errors going from 7.0.1 to 7.0.2

### ISSUE THREAD

**Issue by aBMania** [ChainSafe/js-libp2p-noise#183] opened 2022-08-05 16:42 UTC
Hello, I'm using libp2p with noise v7.0.3 and I've had to downgrade to 7.0.1 since these errors appeared:

Do you know what may cause them ?
I can try to setup a reproducible repo if needed

```
libp2p:upgrader:error Failed to upgrade outbound connection InvalidCryptoExchangeError: Error occurred during XX handshake: xx handshake stage 1 validation fail
    at XXHandshake.exchange (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/handshake-xx.js:48:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Noise.performXXHandshake (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:148:13)
    at async Noise.performHandshake (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:124:20)
    at async Noise.secureOutbound (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:49:27)
    at async EventTarget._encryptOutbound (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/upgrader.js:422:20)
    at async EventTarget.upgradeOutbound (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/upgrader.js:179:17)
    at async TCP.dial (file:///home/node/common/temp/node_modules/.pnpm/@libp2p+tcp@3.0.2/node_modules/@libp2p/tcp/dist/src/index.js:27:22)
    at async EventTarget.dial (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/transport-manager.js:78:20)
    at async DialRequest.dialAction (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:183:20) {
  code: 'ERR_ENCRYPTION_FAILED'
}
```

then later:

```
libp2p:upgrader:error Failed to upgrade inbound connection Error: Error occurred during XX handshake: unexpected end of input
     at decoder (file:///home/node/common/temp/node_modules/.pnpm/it-length-prefixed@8.0.2/node_modules/it-length-prefixed/dist/src/decode.js:74:27)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async Object.readLP (file:///home/node/common/temp/node_modules/.pnpm/it-pb-stream@2.0.1/node_modules/it-pb-stream/dist/src/index.js:18:31)
     at async XXHandshake.finish (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/handshake-xx.js:84:52)
     at async Noise.performXXHandshake (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:149:13)
     at async Noise.performHandshake (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:124:20)
     at async Noise.secureInbound (file:///home/node/common/temp/node_modules/.pnpm/@chainsafe+libp2p-noise@7.0.2/node_modules/@chainsafe/libp2p-noise/dist/src/noise.js:76:27)
     at async EventTarget._encryptInbound (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/upgrader.js:398:20)
     at async EventTarget.upgradeInbound (file:///home/node/common/temp/node_modules/.pnpm/libp2p@0.37.3-e6f646e/node_modules/libp2p/dist/src/upgrader.js:95:17) {
   code: 'ERR_ENCRYPTION_FAILED'
 }
```

Context:

Env: 
docker v20.10.17
docker-compose v2.2.3
node: node:16.14.0-alpine3.14

Dependencies versions:
@chainsafe/libp2p-gossipsub: 3.5.0
@chainsafe/libp2p-noise: 7.0.2
@libp2p/bootstrap: 2.0.0
@libp2p/crypto: 1.0.0
@libp2p/floodsub: 3.0.2
@libp2p/interface-connection: 2.1.1
@libp2p/interface-peer-id: 1.0.4
@libp2p/interface-pubsub: 1.0.4
@libp2p/interface-transport: 1.0.2
@libp2p/interfaces: 3.0.3
@libp2p/kad-dht: 3.0.0
@libp2p/mplex: 4.0.2
@libp2p/peer-id-factory: 1.0.16
@libp2p/pubsub-peer-discovery: 6.0.0
@libp2p/tcp: 3.0.2
@libp2p/websockets: 3.0.1
@multiformats/multiaddr: 10.1.8
@noble/ed25519: 1.6.1
typescript: 4.5.5
it-first: 1.0.7
it-length-prefixed: 7.0.1
it-map: 1.0.6
it-pipe: 2.0.3
it-pushable: 3.0.0
libp2p: 0.37.3-e6f646e

**Comment by mpetrunic** [comment] 2022-08-08 09:34
Huh tnx for reporting, will check with our interop tests

**Comment by mpetrunic** [comment] 2022-08-09 11:32
I can replicate upgrader error but for me, it doesn't error on Stage 1 verification. Will continue debugging

**Comment by mpetrunic** [comment] 2022-08-10 13:37
Closing as error is related to either it-length-prefixed or it-handshake or both 🤷🏻 You should stay on 7.0.1 until we sort those out in libp2p

Same error happens with Plaintext encryptor from libp2p.
cc @achingbrain @wemeetagain

**Comment by wemeetagain** [comment] 2022-08-12 16:38
Going to reopen this as a tracking issue since the problem is still not resolved. We're now running into this in https://github.com/ChainSafe/lodestar/pull/4114

**Comment by wemeetagain** [comment] 2022-08-15 17:15
closing since this is no longer happening as of latest noise and nightly libp2p

**Closed by wemeetagain** 2022-08-15 17:15 UTC
